image: debian:stretch-slim

before_script:
  - sed -i 's@/deb.debian.org/@/mirrors.aliyun.com/@g;s@/security.debian.org/@/mirrors.aliyun.com/@g' /etc/apt/sources.list
  - apt-get update && apt-get install -y --no-install-recommends ca-certificates g++-multilib gcc-multilib make curl wget lib32stdc++6

build:
  stage: build
  script:
    - chmod +x ./build/build.sh && ./build/build.sh
  artifacts:
    paths:
      - Release
  cache:
    paths:
      - deps
